import "./globals.css";
import headerData from "../data/HeaderData";
import Header from "../components/Header";
import { primary, secondary } from "../app/fonts/index";
import { cn } from "../utils/shadcn";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 const data =headerData
  return (
    <html lang="en"     className={cn(
        "dark",
        primary.variable,
        secondary.variable,
        "text-base leading-[1.875] text-accent-800 [&.dark]:text-body"
      )}
    > 
      <body
       
      >
        <Header headersContent={data ?? null}/>
        {children}
      </body>
    </html>
  );
}
